- name: 'add PPA php-fpm'
  apt_repository:
    validate_certs: no
    repo: 'ppa:ondrej/php'
    state: present

- name: 'install nginx, php-fpm'
  apt:
    pkg:
      - nginx
      - php8.1-fpm

- name: 'Copy a server configuration'
  copy:
    src: nginx-site-conf
    dest: /etc/nginx/sites-available/default
  notify: restart nginx service

- name: 'nginx conf validation'
  shell: nginx -t
  register: output

- name: 'nginx conf validation output'
  debug:
    var: output.stderr_lines

- name: 'Copy php page'
  copy:
    src: "{{ item }}"
    dest: /var/www/html/
    mode: 0777
  with_fileglob: www/*
  notify: chmod for www folder
  tags: deploy

- name: 'nginx site is'
  debug: msg="http://{{hostvars[inventory_hostname]['ansible_default_ipv4']['address']}}/"