    - name: add PPA php-fpm
      apt_repository:
        validate_certs: no
        repo: 'ppa:ondrej/php'
        state: present

    - name: install nginx, php-fpm
      apt:
        pkg:
        - nginx
        - php8.1-fpm

    - name: Copy a server configuration
      copy:
        src: ../nginx-site-conf
        dest: /etc/nginx/sites-available/default

    - name: nginx conf validation
      shell: nginx -t
      register: output

    - name: nginx conf validation output
      debug:
        var: output.stderr_lines
