- name: Copy php page
  copy:
    src: "{{ item }}"
    dest: /var/www/html/
    mode: 0777
  with_fileglob:
  - ../www/*

- name: chmod for www folder
  file:
    path: /var/www/html
    mode: 0777
    recurse: yes